"""Commit message generation: Ollama-backed with heuristic fallback.

Follows the Conventional Commits specification:
  type(scope): description  ← imperative, ≤72 chars
  Types: feat | fix | refactor | test | docs | chore | perf | style | ci
"""

import re
from dataclasses import dataclass

from code_context.change_intel import ChangedFile, CompactChange, CommitDraft, generate_commit_draft
from code_context.llm.router import LLMRouter


# ── prompt builder ────────────────────────────────────────────────────────────

_SYSTEM = (
    "You are a git commit message writer. "
    "Follow Conventional Commits: type(scope): description. "
    "Types: feat|fix|refactor|test|docs|chore|perf|style|ci. "
    "Rules: imperative mood, max 72 chars, no period at end. "
    "Output ONE line only — the commit message, nothing else."
)

_CHANGE_SYMBOLS = {"added": "+", "modified": "~", "deleted": "-", "renamed": "→"}


def _format_file_line(f: ChangedFile) -> str:
    symbol = _CHANGE_SYMBOLS.get(f.change_type, "?")
    stats = f" (+{f.additions} -{f.deletions})" if f.additions or f.deletions else ""
    return f"  {symbol} {f.path}{stats}"


def _build_prompt(cc: CompactChange) -> str:
    file_lines = "\n".join(_format_file_line(f) for f in cc.files)
    cues = ", ".join(cc.intent_cues) if cc.intent_cues else "none"
    return (
        f"{_SYSTEM}\n\n"
        f"Changed files:\n{file_lines}\n\n"
        f"Intent cues: {cues}\n"
        f"Summary: {cc.summary}\n\n"
        "Commit message:"
    )


def _sanitize(raw: str) -> str:
    """Strip markdown fences, leading bullets, and extra whitespace."""
    text = raw.strip()
    # remove ```...``` fences
    text = re.sub(r"^```[a-z]*\n?", "", text, flags=re.MULTILINE)
    text = re.sub(r"\n?```$", "", text, flags=re.MULTILINE)
    # take only the first non-empty line
    for line in text.splitlines():
        line = line.strip().lstrip("*-").strip()
        if line:
            return line[:72]
    return text[:72]


def _looks_valid(msg: str) -> bool:
    """Basic sanity check: must match conventional commit pattern."""
    return bool(re.match(r"^[a-z]+(\([^)]+\))?!?: .+", msg))


# ── public API ────────────────────────────────────────────────────────────────


@dataclass
class CommitGeneratorConfig:
    local_model: str = "gemma4:latest"
    remote_model: str = "openai/gpt-4o-mini"
    temperature: float = 0.1
    max_tokens: int = 160
    router: LLMRouter | None = None


class CommitGenerator:
    """Generate conventional commit messages via routed providers with heuristic fallback."""

    def __init__(self, config: CommitGeneratorConfig | None = None) -> None:
        self._cfg = config or CommitGeneratorConfig()
        self._router = self._cfg.router

    def generate(self, cc: CompactChange) -> CommitDraft:
        """Return a CommitDraft. Falls back local->remote->heuristic."""
        if not self._router:
            return self._heuristic(cc, note="provider unavailable: router not configured")
        if not self._cfg.local_model and not self._cfg.remote_model:
            return self._heuristic(cc)

        prompt = _build_prompt(cc)
        options = {"temperature": self._cfg.temperature, "max_tokens": self._cfg.max_tokens}
        response = self._router.generate(
            prompt=prompt,
            local_model=self._cfg.local_model,
            remote_model=self._cfg.remote_model,
            options=options,
        )
        if response.ok:
            message = _sanitize(response.text)
            if _looks_valid(message):
                return CommitDraft(
                    message=message,
                    rationale=f"Generated by {response.provider}:{response.model}.",
                    confidence=0.88,
                    fallback=False,
                    source=f"{response.provider}:{response.model}",
                )

            if response.provider != "openrouter" and self._cfg.remote_model:
                remote = self._router.generate(
                    prompt=prompt,
                    local_model=self._cfg.local_model,
                    remote_model=self._cfg.remote_model,
                    options=options,
                    force_provider="openrouter",
                )
                if remote.ok:
                    remote_message = _sanitize(remote.text)
                    if _looks_valid(remote_message):
                        return CommitDraft(
                            message=remote_message,
                            rationale=f"Generated by {remote.provider}:{remote.model}.",
                            confidence=0.88,
                            fallback=False,
                            source=f"{remote.provider}:{remote.model}",
                        )
                    return self._heuristic(cc, note=f"invalid response: {remote_message!r}")
                return self._heuristic(cc, note=remote.error_reason)

            return self._heuristic(cc, note=f"invalid response: {message!r}")

        return self._heuristic(cc, note=response.error_reason)

    # ── internals ─────────────────────────────────────────────────────────

    @staticmethod
    def _heuristic(cc: CompactChange, note: str = "") -> CommitDraft:
        draft = generate_commit_draft(cc)
        if note:
            draft.rationale = f"{draft.rationale} ({note})"
        draft.source = "heuristic"
        return draft
