"""Commit message generation: Ollama-backed with heuristic fallback.

Follows the Conventional Commits specification:
  type(scope): description  ← imperative, ≤72 chars
  Types: feat | fix | refactor | test | docs | chore | perf | style | ci
"""

import re
from dataclasses import dataclass, field

from change_intel import ChangedFile, CompactChange, CommitDraft, generate_commit_draft
from ollama_client import OllamaClient, OllamaConfig, OllamaUnavailableError


# ── prompt builder ────────────────────────────────────────────────────────────

_SYSTEM = (
    "You are a git commit message writer. "
    "Follow Conventional Commits: type(scope): description. "
    "Types: feat|fix|refactor|test|docs|chore|perf|style|ci. "
    "Rules: imperative mood, max 72 chars, no period at end. "
    "Output ONE line only — the commit message, nothing else."
)

_CHANGE_SYMBOLS = {"added": "+", "modified": "~", "deleted": "-", "renamed": "→"}


def _format_file_line(f: ChangedFile) -> str:
    symbol = _CHANGE_SYMBOLS.get(f.change_type, "?")
    stats = f" (+{f.additions} -{f.deletions})" if f.additions or f.deletions else ""
    return f"  {symbol} {f.path}{stats}"


def _build_prompt(cc: CompactChange) -> str:
    file_lines = "\n".join(_format_file_line(f) for f in cc.files)
    cues = ", ".join(cc.intent_cues) if cc.intent_cues else "none"
    return (
        f"{_SYSTEM}\n\n"
        f"Changed files:\n{file_lines}\n\n"
        f"Intent cues: {cues}\n"
        f"Summary: {cc.summary}\n\n"
        "Commit message:"
    )


def _sanitize(raw: str) -> str:
    """Strip markdown fences, leading bullets, and extra whitespace."""
    text = raw.strip()
    # remove ```...``` fences
    text = re.sub(r"^```[a-z]*\n?", "", text, flags=re.MULTILINE)
    text = re.sub(r"\n?```$", "", text, flags=re.MULTILINE)
    # take only the first non-empty line
    for line in text.splitlines():
        line = line.strip().lstrip("*-").strip()
        if line:
            return line[:72]
    return text[:72]


def _looks_valid(msg: str) -> bool:
    """Basic sanity check: must match conventional commit pattern."""
    return bool(re.match(r"^[a-z]+(\([^)]+\))?!?: .+", msg))


# ── public API ────────────────────────────────────────────────────────────────


@dataclass
class CommitGeneratorConfig:
    model: str = "gemma4:latest"
    ollama: OllamaConfig = field(default_factory=OllamaConfig)
    temperature: float = 0.1


class CommitGenerator:
    """Generate conventional commit messages via Ollama with heuristic fallback."""

    def __init__(self, config: CommitGeneratorConfig | None = None) -> None:
        self._cfg = config or CommitGeneratorConfig()
        self._client = OllamaClient(self._cfg.ollama)

    def generate(self, cc: CompactChange) -> CommitDraft:
        """Return a CommitDraft.  Falls back to heuristic if Ollama unavailable."""
        if not self._cfg.model:
            return self._heuristic(cc)

        try:
            raw = self._client.generate(
                model=self._cfg.model,
                prompt=_build_prompt(cc),
                temperature=self._cfg.temperature,
            )
            message = _sanitize(raw)
            if not _looks_valid(message):
                return self._heuristic(cc, note=f"model output invalid: {message!r}")
            return CommitDraft(
                message=message,
                rationale=f"Generated by {self._cfg.model}.",
                confidence=0.88,
                fallback=False,
                source=f"ollama:{self._cfg.model}",
            )
        except OllamaUnavailableError as exc:
            return self._heuristic(cc, note=str(exc))

    # ── internals ─────────────────────────────────────────────────────────

    @staticmethod
    def _heuristic(cc: CompactChange, note: str = "") -> CommitDraft:
        draft = generate_commit_draft(cc)
        if note:
            draft.rationale = f"{draft.rationale} (ollama unavailable: {note})"
        draft.source = "heuristic"
        return draft
